### ISSUE TITLE
Doesn't install on windows 8, breaks jsDAV and cloud9 ide

### ISSUE THREAD

**Issue by Fire-** [c9/node-gnu-tools#11]
Windows 8 Pro x64
node 0.10.5
npm 1.2.18
Trying to install Cloud9 IDE following their windows instructions.
Cygwin grep was already installed and in-path, didn't work.
Tried installing gnuwin32 grep, added to path, didn't work.
Removed cygwin grep from path to avoid path conflict, didn't work.
This package refuses to detect grep, even when it clearly exists on the system.

```
C:\projects\js\cloud9>npm install gnu-tools
npm http GET https://registry.npmjs.org/gnu-tools
npm http 200 https://registry.npmjs.org/gnu-tools
npm WARN package.json gnu-tools@0.0.8 No README.md file found!

> gnu-tools@0.0.8 postinstall C:\projects\js\cloud9\node_modules\gnu-tools
> node ./install.js

path.existsSync is now called `fs.existsSync`.
Creating directory  C:\projects\js\cloud9\node_modules\gnu-tools/bin
path.exists is now called `fs.exists`.
[Error: You need some version of `grep` on your PATH to compile the gnu-tools version of grep!] 'Error: You need some version of `grep` on your PATH to compile the gnu-tools version of grep!\n    at C:\\projects\\js\\cloud9\\node_modules\\gnu-tools\\install.js:38:18\n    at C:\\projects\\js\\cloud9\\node_modules\\gnu-tools\\install.js:117:17\n    at Object.cb [as oncomplete] (fs.js:168:19)'
npm ERR! gnu-tools@0.0.8 postinstall: `node ./install.js`
npm ERR! `cmd "/c" "node ./install.js"` failed with 1
npm ERR!
npm ERR! Failed at the gnu-tools@0.0.8 postinstall script.
npm ERR! This is most likely a problem with the gnu-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gnu-tools
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "gnu-tools"
npm ERR! cwd C:\projects\js\cloud9
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\projects\js\cloud9\npm-debug.log
npm ERR! not ok code 0
```

```
C:\projects\js\cloud9>npm install jsDAV
npm http GET https://github.com/ajaxorg/jsDAV/tarball/f78c34c94fa915ca1b24975839b78ff88ea851d6
npm http 200 https://github.com/ajaxorg/jsDAV/tarball/f78c34c94fa915ca1b24975839b78ff88ea851d6
npm http GET https://github.com/ajaxorg/jsftp/tarball/97d65da1c29f3bc9b1a2363431b87a7bc9520373
npm http GET https://registry.npmjs.org/asyncjs/0.0.8
npm http GET https://registry.npmjs.org/formidable/1.0.9
npm http GET https://registry.npmjs.org/node-sftp/0.1.1
npm http GET https://registry.npmjs.org/gnu-tools/0.0.8
npm http GET https://registry.npmjs.org/xmldom/0.1.2
npm http 304 https://registry.npmjs.org/formidable/1.0.9
npm http 304 https://registry.npmjs.org/gnu-tools/0.0.8
npm http 304 https://registry.npmjs.org/node-sftp/0.1.1
npm http 304 https://registry.npmjs.org/xmldom/0.1.2
npm http 304 https://registry.npmjs.org/asyncjs/0.0.8
npm WARN package.json gnu-tools@0.0.8 No README.md file found!
npm http 200 https://github.com/ajaxorg/jsftp/tarball/97d65da1c29f3bc9b1a2363431b87a7bc9520373
npm http GET https://registry.npmjs.org/streamer
npm http 304 https://registry.npmjs.org/streamer

> gnu-tools@0.0.8 postinstall C:\projects\js\cloud9\node_modules\jsDAV\node_modules\gnu-tools
> node ./install.js

path.existsSync is now called `fs.existsSync`.
Creating directory  C:\projects\js\cloud9\node_modules\jsDAV\node_modules\gnu-tools/bin
path.exists is now called `fs.exists`.
[Error: You need some version of `grep` on your PATH to compile the gnu-tools version of grep!] 'Error: You need some version of `grep` on your PATH to compile the gnu-tools version of grep!\n    at C:\\projects\\js\\cloud9\\node_modules\\jsDAV\\node_modules\\gnu-tools\\install.js:38:18\n    at C:\\projects\\js\\cloud9\\node_modules\\jsDAV\\node_modules\\gnu-tools\\install.js:117:17\n    at Object.cb [as oncomplete] (fs.js:168:19)'
npm ERR! gnu-tools@0.0.8 postinstall: `node ./install.js`
npm ERR! `cmd "/c" "node ./install.js"` failed with 1
npm ERR!
npm ERR! Failed at the gnu-tools@0.0.8 postinstall script.
npm ERR! This is most likely a problem with the gnu-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gnu-tools
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "jsDAV"
npm ERR! cwd C:\projects\js\cloud9
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\projects\js\cloud9\npm-debug.log
npm ERR! not ok code 0
```

**Comment by ionutvmi** [comment]
@9suns thanks ! also make sure you run the shell as Administrator

**Comment by Moytri** [comment]
How to install cloud9 on window 8.1 ? Need suggestion .

**Comment by nightwing** [comment]
@Moytri see https://github.com/c9/core,
Cloud9 doesn't use node-gnu-tools and jsdav anymore.
